### PR TITLE
VCAP-14405 Migrate sample capsules to use the new version of viv.self…

### PR DESCRIPTION
**Pull request by dylandavidson95**
… library (which is not importing viv.contact anymore)

### CODE REVIEW

**Review by vboughner — COMMENTED** [review]
Did you mean to change the indentation in `capsule.bxb`? Doing so makes it harder to see the specific changes made there. You might consider restoring the indentation to two spaces (unless I'm unaware of some standard practices on the capsule team surrounding indentation).

This is a good update, it's interesting to see how the use of the `viv.self` capsule is evolving. I haven't had the pleasure of using it myself, so I'll leave review of that part up to someone else. Nice work! 🚀

**Comment by DogeThis** [comment]
> Did you mean to change the indentation in `capsule.bxb`? Doing so makes it harder to see the specific changes made there. You might consider restoring the indentation to two spaces (unless I'm unaware of some standard practices on the capsule team surrounding indentation).
> 
> This is a good update, it's interesting to see how the use of the `viv.self` capsule is evolving. I haven't had the pleasure of using it myself, so I'll leave review of that part up to someone else. Nice work! 🚀

The indenting comes from the IDE's autoindent feature.

**Comment by dylandavidson95** [comment]
Yes, auto-indent changed the indentation.
I also just realized that uncommenting 
```
permissions { user-profile-access }
```
broke the stories, so please do not merge until I commit a fix for that

**Comment by dylandavidson95** [comment]
everything is good to go now 👍

**Comment by vboughner** [comment]
If you'd like to avoid having all those web cache files checked-in, you can use the "Clear Cache" button on that story after running it the last time, and check in the changes after that. It will delete all the cached files, which future users of the sample capsule can regenerate later by running the story "Live".

I leave the web cache files out of my checkins for My Brain capsule, for example, because they would reveal the secret client api key in the open source github repo.

**Comment by dylandavidson95** [comment]
Thanks for the tip! I cleared it

**Review by siamakh — APPROVED** [review]

**Pull request merged**
