### PR TITLE
Update items soon to be deprecated (6830)

### PR DESCRIPTION
**Pull request by bispodv**
These changes due to deprecation are being submitted due to some updates that were not made the last time

### CODE REVIEW

**Review by adanis — APPROVED** [review]
These look good to me!

**Comment by adanis** [comment]
Is it possible to also update the macros in the `ko-KR` folders? The invocation and definitions should change, but the actual text can stay exactly the same.

**Comment by bispodv** [comment]
Updated `ko-KR` resources as suggested. Thanks @adanis

**Comment by abapayeViv** [comment]
LGTM!

@rogerkibbe Please merge this PR.

**Review by abapayeViv — APPROVED** [review]
👍

**Pull request merged**
